-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/GlobalPreferences/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/global_preferences (
  gp_user INTEGER UNSIGNED NOT NULL,
  gp_property BLOB NOT NULL,
  gp_value BLOB DEFAULT NULL,
  PRIMARY KEY(gp_user, gp_property)
);

CREATE INDEX global_preferences_property ON /*_*/global_preferences (gp_property);
